version: '3'
services:
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    image: {{ cookiecutter.github_repo }}:${TAG:-latest}
    volumes:
      - ${HOST_DIR}:/home/jovyan/work
      - ${CERT_DIR}:/etc/ssl/notebook
    user: 'root' # passwordless sudo
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
      NB_USER: '{{ cookiecutter.notebook_username }}'
      CHOWN_HOME: 'yes'
      GEN_CERT: 'yes'
      RESTARTABLE: 'yes'
    ports:
      - ${PORT:-0}:8888
    command: "start-notebook.sh \
              --NotebookApp.disable_check_xsrf=True \
              --NotebookApp.password=${PASSWD}"

