#!/bin/bash

[ -d .dddlab/keys ] || mkdir -p .dddlab/keys

## Self-signed certificates can be generated according to
## https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#using-ssl-for-encrypted-communication

openssl req -x509 -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout .dddlab/keys/mykey.key \
    -out .dddlab/keys/mycert.pem \
    -subj "/C=US/ST=A/L=B/O=C/OU=D/CN=F"

## utility for hashing notebook password 

curl -fsSL https://github.com/dddlab/jupyter-passwd/releases/download/v0.1.1/hash-password \
    -o .dddlab/hash-password && \
    chmod u+x .dddlab/hash-password
# https://github.com/docker/compose/issues/4223#issuecomment-280077263
# https://docs.docker.com/compose/environment-variables/

cat <<EOF > .env
## generated by setup.sh
## variables for docker-compose

HOST_DIR=${PWD}
CERT_DIR=${PWD}/.dddlab/keys
PASSWD=$(.dddlab/hash-password | tail -n1)
EOF
