#!/bin/bash

[ -d .dddlab/keys ] || mkdir -p .dddlab/keys


echo "### Generate keys for https encryption"
openssl req -x509 -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout .dddlab/keys/mykey.key \
    -out .dddlab/keys/mycert.pem \
    -subj "/C=US/ST=A/L=B/O=C/OU=D/CN=F" && \
    chmod a+r .dddlab/keys/mykey.key

echo "### download password generating utility"
curl -s -L https://gist.githubusercontent.com/syoh/8f36035ed06349842ab74c037cc2a847/raw/64086f17933349f7b94d2e4f9743bf941d44590a/hash-password.sh -o .dddlab/hash-password.sh && chmod +x .dddlab/hash-password.sh

cat <<EOF > .env
## generated by setup.sh
## variables for docker-compose

HOST_DIR=${PWD}
CERT_DIR=${PWD}/.dddlab/keys
PASSWD=$(.dddlab/hash-password.sh)
EOF
