#!/bin/bash

[ -d home ] || mkdir home
[ -d keys ] || mkdir keys

## Self-signed certificates can be generated according to
## https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#using-ssl-for-encrypted-communication

openssl req -x509 -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout keys/mykey.key \
    -out keys/mycert.pem \
    -subj "/C=US/ST=A/L=B/O=C/OU=D/CN=F"

## download utility for hashing jupyter notebook password
wget -nc https://github.com/dddlab/jupyter-passwd/releases/download/v0.0.1.6/hash-password \
    -O .dddlab/hash-password && \
    chmod u+x .dddlab/hash-password

## https://github.com/docker/compose/issues/4223#issuecomment-280077263
## https://docs.docker.com/compose/environment-variables/

cat <<EOF > .env
## generated by setup.sh
## docker-compose variables

HOST_DIR=${PWD}/home
CERT_DIR=${PWD}/keys
PASSWD=$(.dddlab/hash-password)
EOF
