name: Build notebook image

on: 
  push:
    branches:
      - docker
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build-notebook-image:

    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set notebook env variables
        id: set_env_notebook
        run: |
          echo "::set-output name=image::{{cookiecutter.target_docker_image}}"
          echo "::set-output name=tag::sha-${GITHUB_SHA::7}"

      - name: Build notebook image
        uses: docker/build-push-action@v1.1.0
        with:
          {% raw -%}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ steps.set_env_notebook.outputs.image }}
          {% endraw -%}
          tag_with_sha: true
          tags: latest
      
  {% raw -%}
  create-release:

    name: Create Release
    runs-on: ubuntu-latest
    needs: build-notebook-image
    if: ${{ contains(github.ref, 'tags/v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.set_env_notebook.outputs.image }}:${{ steps.set_env_notebook.outputs.tag }}:
          draft: false
          prerelease: false
  {% endraw -%}
